-- 1. Bảng Projects quản lý dự án
create table if not exists public.projects (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  created_at timestamptz default now()
);
alter table public.projects enable row level security;

-- 2. Bảng Profiles quản lý phân quyền
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  role text default 'Member',
  full_name text
);
alter table public.profiles enable row level security;

-- 3. Bảng Project Members (Phân quyền theo dự án)
create table if not exists public.project_members (
  project_id uuid references public.projects(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  role text default 'Member',
  primary key (project_id, user_id)
);
alter table public.project_members enable row level security;

-- 4. Trigger tự động tạo profile
create or replace function public.handle_new_user() returns trigger as $$
begin
  insert into public.profiles (id, full_name) values (new.id, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- 5. Bảng Skill Pool (Danh mục kỹ năng dùng chung theo dự án)
create table if not exists public.skill_pool (
  id bigint generated by default as identity primary key,
  name text not null,
  project_id uuid references public.projects(id) on delete cascade
);
alter table public.skill_pool enable row level security;

-- 6. Bảng Members (Thành viên / Nhân sự)
create table if not exists public.members (
  id bigint generated by default as identity primary key,
  project_id uuid references public.projects(id) on delete cascade,
  name text not null,
  email text not null,
  available_hours int default 10,
  tags text[] default '{}'::text[]
);
alter table public.members enable row level security;

-- 7. Bảng Tasks (Công việc)
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  project_id uuid references public.projects(id) on delete cascade,
  name text not null,
  hours int default 4,
  priority text default 'Trung bình',
  status text default 'To Do',
  assignee_id bigint references public.members(id) on delete set null,
  tags text[] default '{}'::text[]
);
alter table public.tasks enable row level security;

-- 8. Hàm Mapping (RPC) trong Postgres
create or replace function public.run_mapping(p_project_id uuid)
returns jsonb language plpgsql security definer as $$
begin
  return jsonb_build_object('status', 'success', 'message', 'Mapping completed successfully for project ' || p_project_id);
end;
$$;
